apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  template:
    spec:
      # Volumes for KSOPS and SOPS age key
      volumes:
      - name: custom-tools
        emptyDir: {}
      - name: sops-age
        secret:
          secretName: sops-age

      # Init container to install KSOPS
      initContainers:
      - name: install-ksops
        image: viaductoss/ksops:v4.3.2
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "Installing KSOPS and kustomize...";
          cp ksops /custom-tools/;
          cp $GOPATH/bin/kustomize /custom-tools/;
          chmod +x /custom-tools/ksops /custom-tools/kustomize;
          echo "KSOPS installation complete.";
        volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools

      containers:
      - name: argocd-repo-server
        # Mount custom tools and age key
        volumeMounts:
        - mountPath: /usr/local/bin/ksops
          name: custom-tools
          subPath: ksops
        - mountPath: /usr/local/bin/kustomize
          name: custom-tools
          subPath: kustomize
        - mountPath: /home/argocd/.config/sops/age
          name: sops-age
          readOnly: true

        # Environment variables for SOPS
        env:
        - name: XDG_CONFIG_HOME
          value: /home/argocd/.config
        - name: SOPS_AGE_KEY_FILE
          value: /home/argocd/.config/sops/age/keys.txt
        - name: KUSTOMIZE_PLUGIN_HOME
          value: /usr/local/bin
