set number
set relativenumber
set tabstop=2
set shiftwidth=2
set expandtab
set smartindent
set autoindent
set hlsearch
set incsearch
set ignorecase
set smartcase
set cursorline
set showmatch
set wildmenu
set wildmode=longest:full,full
set backspace=indent,eol,start
set encoding=utf-8
set fileencoding=utf-8
syntax on