#!/usr/bin/env bash
# ============================================================================
# IMMEDIATE ACTION ITEMS - Goblin Assistant Chat Fix
# ============================================================================
#
# Issues to fix:
# ❌ Router returns "All servers unavailable" when trying to reach Inference
# ❌ End-to-end chat completions failing
#
# Root Cause: 
# - Firewall blocks traffic between servers
# - Router configured with wrong Inference IP (172.16.0.1 instead of 192.175.23.150)
#
# ============================================================================

echo ""
echo "╔════════════════════════════════════════════════════════════════════════╗"
echo "║  🚀 GOBLIN ASSISTANT CHAT FIX - IMMEDIATE ACTION REQUIRED              ║"
echo "╚════════════════════════════════════════════════════════════════════════╝"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "OPTION 1: AUTOMATED FIX (RECOMMENDED) ⚡"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run this script:"
echo "  cd /Users/fuaadabdullah/ForgeMonorepo"
echo "  bash kamatera_infrastructure_fix.sh"
echo ""
echo "What it does:"
echo "  ✓ Configures firewall on both servers"
echo "  ✓ Updates Router INFERENCE_URL configuration"
echo "  ✓ Restarts both services"
echo "  ✓ Tests connectivity"
echo "  ✓ Tests chat completion"
echo "  ✓ Shows results"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "OPTION 2: MANUAL STEPS (IF AUTOMATED SCRIPT FAILS)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Step 1: Firewall on Inference Server (192.175.23.150)"
echo "  ssh root@192.175.23.150"
echo "  sudo ufw allow from 45.61.51.220 to any port 8002"
echo ""
echo "Step 2: Firewall on Router Server (45.61.51.220)"
echo "  ssh root@45.61.51.220"
echo "  sudo ufw allow out to 192.175.23.150 port 8002"
echo ""
echo "Step 3: Update Router Configuration"
echo "  ssh root@45.61.51.220"
echo "  sudo sed -i 's|Environment=\"INFERENCE_URL=.*\"|Environment=\"INFERENCE_URL=http://192.175.23.150:8002\"|' /etc/systemd/system/goblin-router.service"
echo "  sudo systemctl daemon-reload"
echo "  sudo systemctl restart goblin-router"
echo ""
echo "Step 4: Restart Inference Server"
echo "  ssh root@192.175.23.150"
echo "  sudo systemctl restart local-llm-proxy"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "VERIFICATION STEPS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "After applying the fix, verify with:"
echo ""
echo "1. Test connectivity from Router to Inference:"
echo "   ssh root@45.61.51.220"
echo "   timeout 5 bash -c 'echo > /dev/tcp/192.175.23.150/8002' && echo '✅ OK' || echo '❌ FAIL'"
echo ""
echo "2. Test Router health endpoint:"
echo "   curl http://45.61.51.220:8000/health"
echo ""
echo "3. Test chat completion:"
echo "   curl -X POST http://45.61.51.220:8000/v1/chat/completions \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"model\":\"llama2:7b\",\"messages\":[{\"role\":\"user\",\"content\":\"Hello\"}]}'"
echo ""
echo "4. Test frontend:"
echo "   Open: https://goblin.fuaad.ai"
echo "   Send test message and verify you get a response"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TROUBLESHOOTING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "If chat still returns 'All servers unavailable':"
echo ""
echo "1. Check Router logs:"
echo "   ssh root@45.61.51.220 'sudo journalctl -u goblin-router -n 20 --no-pager'"
echo ""
echo "2. Check firewall rules:"
echo "   ssh root@45.61.51.220 'sudo ufw status'"
echo "   ssh root@192.175.23.150 'sudo ufw status'"
echo ""
echo "3. Test port directly:"
echo "   ssh root@45.61.51.220 'nc -zv 192.175.23.150 8002'"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "DOCUMENTATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "For detailed information, see:"
echo "  • GOBLIN_CHAT_FIX_SUMMARY.md - Overview and quick reference"
echo "  • ROUTER_NETWORK_FIX_CLEAN.md - Comprehensive implementation guide"
echo "  • kamatera_manual_fix_guide.sh - Step-by-step manual instructions"
echo ""

echo "╔════════════════════════════════════════════════════════════════════════╗"
echo "║  Ready to fix! Run one of the options above.                           ║"
echo "╚════════════════════════════════════════════════════════════════════════╝"
echo ""
