#!/bin/bash

##############################################################################
# DuckDNS Setup for Goblin Assistant on GCP
# 
# This script configures DuckDNS dynamic DNS for the customer-facing 
# Goblin Assistant deployed on Google Cloud Platform (GCP)
#
# Prerequisites:
# 1. GCP VM instance running with a public IP
# 2. DuckDNS account at https://www.duckdns.org
# 3. Registered subdomain (e.g., goblinossistant, goblinai)
# 4. DuckDNS token from your dashboard
##############################################################################

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
DUCKDNS_DOMAIN="${DUCKDNS_DOMAIN:-goblinossistant}"  # Change to your preferred subdomain
DUCKDNS_TOKEN="${DUCKDNS_TOKEN:-}"
DUCKDNS_UPDATE_SCRIPT="/usr/local/bin/duckdns-update.sh"
DUCKDNS_CRON_LOG="/var/log/duckdns.log"
DEPLOYMENT_TYPE="gcp"  # GCP deployment

echo -e "${BLUE}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║     DuckDNS Setup for Goblin Assistant (GCP)            ║${NC}"
echo -e "${BLUE}╚══════════════════════════════════════════════════════════╝${NC}"
echo ""

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   echo -e "${RED}❌ This script must be run as root (use sudo)${NC}"
   exit 1
fi

# Get DuckDNS token if not provided
if [ -z "$DUCKDNS_TOKEN" ]; then
    echo -e "${YELLOW}📝 DuckDNS Token Required${NC}"
    echo ""
    echo "To get your token:"
    echo "  1. Visit https://www.duckdns.org"
    echo "  2. Log in with your account"
    echo "  3. Copy your token from the top of the page"
    echo ""
    read -p "Enter your DuckDNS token: " DUCKDNS_TOKEN
    
    if [ -z "$DUCKDNS_TOKEN" ]; then
        echo -e "${RED}❌ DuckDNS token is required!${NC}"
        exit 1
    fi
fi

# Get domain if not provided
echo ""
echo -e "${YELLOW}🌐 DuckDNS Subdomain Configuration${NC}"
echo ""
echo "Customer-facing domain suggestions:"
echo "  - goblinossistant (recommended - professional)"
echo "  - goblinai (short and memorable)"
echo "  - goblin-chat (descriptive)"
echo "  - goblinhelp (friendly)"
echo ""
echo "Your public domain will be: <subdomain>.duckdns.org"
echo ""
read -p "Enter your DuckDNS subdomain [$DUCKDNS_DOMAIN]: " input_domain
DUCKDNS_DOMAIN="${input_domain:-$DUCKDNS_DOMAIN}"

echo ""
echo -e "${GREEN}✅ Configuration:${NC}"
echo "   Domain: ${DUCKDNS_DOMAIN}.duckdns.org"
echo "   Token: ${DUCKDNS_TOKEN:0:8}..."
echo "   Platform: Google Cloud Platform (GCP)"
echo ""

# Get current public IP from GCP metadata or public service
echo -e "${BLUE}🔍 Detecting GCP public IP address...${NC}"

# Try GCP metadata first (if on GCP VM)
PUBLIC_IP=$(curl -s -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip 2>/dev/null || curl -s https://api.ipify.org)

if [ -z "$PUBLIC_IP" ]; then
    echo -e "${RED}❌ Could not detect public IP address${NC}"
    exit 1
fi

echo -e "${GREEN}   Public IP: $PUBLIC_IP${NC}"
echo ""

# Test DuckDNS API
echo -e "${BLUE}🧪 Testing DuckDNS API connection...${NC}"
RESPONSE=$(curl -s "https://www.duckdns.org/update?domains=${DUCKDNS_DOMAIN}&token=${DUCKDNS_TOKEN}&ip=${PUBLIC_IP}")

if [ "$RESPONSE" = "OK" ]; then
    echo -e "${GREEN}✅ DuckDNS updated successfully!${NC}"
else
    echo -e "${RED}❌ DuckDNS update failed: $RESPONSE${NC}"
    echo ""
    echo "Possible issues:"
    echo "  - Invalid token"
    echo "  - Subdomain not registered at duckdns.org"
    echo "  - Network connectivity problem"
    exit 1
fi

# Create DuckDNS update script
echo ""
echo -e "${BLUE}📝 Creating DuckDNS update script...${NC}"
cat > "$DUCKDNS_UPDATE_SCRIPT" << EOF
#!/bin/bash
# DuckDNS Update Script for Goblin Assistant (GCP)
# Auto-generated by setup-duckdns-gcp.sh

# Try GCP metadata first, fallback to public API
CURRENT_IP=\$(curl -s -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip 2>/dev/null || curl -s https://api.ipify.org)

# Update DuckDNS
RESPONSE=\$(curl -s "https://www.duckdns.org/update?domains=${DUCKDNS_DOMAIN}&token=${DUCKDNS_TOKEN}&ip=\${CURRENT_IP}")

# Log the result
TIMESTAMP=\$(date '+%Y-%m-%d %H:%M:%S')
if [ "\$RESPONSE" = "OK" ]; then
    echo "[\$TIMESTAMP] ✅ DuckDNS updated: ${DUCKDNS_DOMAIN}.duckdns.org -> \$CURRENT_IP" >> ${DUCKDNS_CRON_LOG}
    exit 0
else
    echo "[\$TIMESTAMP] ❌ DuckDNS update failed: \$RESPONSE" >> ${DUCKDNS_CRON_LOG}
    exit 1
fi
EOF

chmod +x "$DUCKDNS_UPDATE_SCRIPT"
echo -e "${GREEN}✅ Update script created: $DUCKDNS_UPDATE_SCRIPT${NC}"

# Create log file
touch "$DUCKDNS_CRON_LOG"
chmod 644 "$DUCKDNS_CRON_LOG"

# Setup cron job to update every 5 minutes
echo ""
echo -e "${BLUE}⏰ Setting up automatic updates (every 5 minutes)...${NC}"

# Remove existing DuckDNS cron jobs
crontab -l 2>/dev/null | grep -v "duckdns-update.sh" | crontab - || true

# Add new cron job
(crontab -l 2>/dev/null; echo "*/5 * * * * $DUCKDNS_UPDATE_SCRIPT") | crontab -

echo -e "${GREEN}✅ Cron job configured${NC}"

# Create environment file for docker-compose
echo ""
echo -e "${BLUE}📄 Creating environment configuration...${NC}"
ENV_FILE="/root/goblin-assistant/.env.duckdns"
mkdir -p /root/goblin-assistant
cat > "$ENV_FILE" << EOF
# DuckDNS Configuration for Goblin Assistant (GCP Deployment)
DUCKDNS_DOMAIN=${DUCKDNS_DOMAIN}
DUCKDNS_TOKEN=${DUCKDNS_TOKEN}
DUCKDNS_FULL_DOMAIN=${DUCKDNS_DOMAIN}.duckdns.org
PUBLIC_IP=${PUBLIC_IP}
DEPLOYMENT_PLATFORM=gcp

# Update these in your main .env file:
BACKEND_URL=https://${DUCKDNS_DOMAIN}.duckdns.org
FRONTEND_URL=https://${DUCKDNS_DOMAIN}.duckdns.org
API_BASE_URL=https://${DUCKDNS_DOMAIN}.duckdns.org/api

# GCP LLM Endpoints (already configured)
OLLAMA_GCP_URL=http://34.60.255.199:11434
LLAMACPP_GCP_URL=http://34.132.226.143:8000
EOF

chmod 600 "$ENV_FILE"
echo -e "${GREEN}✅ Environment file created: $ENV_FILE${NC}"

# Display nginx configuration suggestion
echo ""
echo -e "${BLUE}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║     Next Steps: Nginx & SSL Configuration (GCP)         ║${NC}"
echo -e "${BLUE}╚══════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${YELLOW}1. Install Certbot for SSL:${NC}"
echo "   sudo apt-get update"
echo "   sudo apt-get install -y certbot python3-certbot-nginx"
echo ""
echo -e "${YELLOW}2. Get SSL certificate:${NC}"
echo "   sudo certbot --nginx -d ${DUCKDNS_DOMAIN}.duckdns.org"
echo ""
echo -e "${YELLOW}3. Configure GCP Firewall:${NC}"
echo "   gcloud compute firewall-rules create allow-https \\"
echo "     --allow tcp:443 \\"
echo "     --source-ranges 0.0.0.0/0 \\"
echo "     --target-tags http-server,https-server"
echo ""
echo -e "${YELLOW}4. Update nginx configuration:${NC}"
echo "   Edit /etc/nginx/sites-available/goblin-assistant"
echo "   Update server_name to: ${DUCKDNS_DOMAIN}.duckdns.org"
echo ""
echo -e "${YELLOW}5. Update Goblin Assistant environment:${NC}"
echo "   Source the DuckDNS environment file:"
echo "   source $ENV_FILE"
echo ""
echo -e "${YELLOW}6. Restart services:${NC}"
echo "   sudo systemctl restart nginx"
echo "   docker-compose restart"
echo ""
echo -e "${GREEN}✅ DuckDNS Setup Complete!${NC}"
echo ""
echo -e "${BLUE}Your customer-facing domain: https://${DUCKDNS_DOMAIN}.duckdns.org${NC}"
echo ""
echo -e "${YELLOW}📊 Monitor updates:${NC}"
echo "   tail -f $DUCKDNS_CRON_LOG"
echo ""
echo -e "${YELLOW}🔄 Manual update:${NC}"
echo "   sudo $DUCKDNS_UPDATE_SCRIPT"
echo ""
echo -e "${BLUE}🔗 GCP Resources:${NC}"
echo "   - Console: https://console.cloud.google.com"
echo "   - VM Instances: https://console.cloud.google.com/compute/instances"
echo "   - Firewall Rules: https://console.cloud.google.com/networking/firewalls"
echo ""
