apiVersion: v1
kind: Namespace
metadata:
  name: goblinos-ai
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-inference
  namespace: goblinos-ai
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ollama-inference
  template:
    metadata:
      labels:
        app: ollama-inference
    spec:
      containers:
      - name: ollama
        image: ollama/local-inference:latest
        ports:
        - containerPort: 8080
        env:
        - name: AZURE_AI_ENDPOINT
          value: "<azure-endpoint-url>"
        - name: GCP_AI_ENDPOINT
          value: "<gcp-endpoint-url>"
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: goblinos-ai
spec:
  selector:
    app: ollama-inference
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP