name: Forge Lite API CI

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/forge-lite/api/**'
      - '.github/workflows/forge-lite-api-ci.yml'
  pull_request:
    paths:
      - 'apps/forge-lite/api/**'
      - '.github/workflows/forge-lite-api-ci.yml'

jobs:
  pytest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/forge-lite/api
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: apps/forge-lite/api/requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: pytest -q

