#!/bin/bash

##############################################################################
# DuckDNS Setup for Goblin Assistant
# 
# This script configures DuckDNS dynamic DNS for the Goblin Assistant,
# giving it a public domain like goblinossistant.duckdns.org
#
# Prerequisites:
# 1. Create a DuckDNS account at https://www.duckdns.org
# 2. Register a subdomain (e.g., goblinossistant, goblinai, goblinos-assistant)
# 3. Get your DuckDNS token from the dashboard
##############################################################################

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
DUCKDNS_DOMAIN="${DUCKDNS_DOMAIN:-goblinossistant}"  # Change this to your preferred subdomain
DUCKDNS_TOKEN="${DUCKDNS_TOKEN:-}"
DUCKDNS_UPDATE_SCRIPT="/usr/local/bin/duckdns-update.sh"
DUCKDNS_CRON_LOG="/var/log/duckdns.log"

echo -e "${BLUE}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║     DuckDNS Setup for Goblin Assistant                  ║${NC}"
echo -e "${BLUE}╚══════════════════════════════════════════════════════════╝${NC}"
echo ""

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   echo -e "${RED}❌ This script must be run as root (use sudo)${NC}"
   exit 1
fi

# Get DuckDNS token if not provided
if [ -z "$DUCKDNS_TOKEN" ]; then
    echo -e "${YELLOW}📝 DuckDNS Token Required${NC}"
    echo ""
    echo "To get your token:"
    echo "  1. Visit https://www.duckdns.org"
    echo "  2. Log in with your account"
    echo "  3. Copy your token from the top of the page"
    echo ""
    read -p "Enter your DuckDNS token: " DUCKDNS_TOKEN
    
    if [ -z "$DUCKDNS_TOKEN" ]; then
        echo -e "${RED}❌ DuckDNS token is required!${NC}"
        exit 1
    fi
fi

# Get domain if not provided
echo ""
echo -e "${YELLOW}🌐 DuckDNS Subdomain Configuration${NC}"
echo ""
echo "Available subdomain suggestions:"
echo "  - goblinossistant (recommended)"
echo "  - goblinai"
echo "  - goblinos-assistant"
echo "  - goblin-chat"
echo "  - goblindev"
echo ""
echo "Your domain will be: <subdomain>.duckdns.org"
echo ""
read -p "Enter your DuckDNS subdomain [$DUCKDNS_DOMAIN]: " input_domain
DUCKDNS_DOMAIN="${input_domain:-$DUCKDNS_DOMAIN}"

echo ""
echo -e "${GREEN}✅ Configuration:${NC}"
echo "   Domain: ${DUCKDNS_DOMAIN}.duckdns.org"
echo "   Token: ${DUCKDNS_TOKEN:0:8}..."
echo ""

# Get current public IP
echo -e "${BLUE}🔍 Detecting public IP address...${NC}"
PUBLIC_IP=$(curl -s https://api.ipify.org)
echo -e "${GREEN}   Public IP: $PUBLIC_IP${NC}"
echo ""

# Test DuckDNS API
echo -e "${BLUE}🧪 Testing DuckDNS API connection...${NC}"
RESPONSE=$(curl -s "https://www.duckdns.org/update?domains=${DUCKDNS_DOMAIN}&token=${DUCKDNS_TOKEN}&ip=${PUBLIC_IP}")

if [ "$RESPONSE" = "OK" ]; then
    echo -e "${GREEN}✅ DuckDNS updated successfully!${NC}"
else
    echo -e "${RED}❌ DuckDNS update failed: $RESPONSE${NC}"
    echo ""
    echo "Possible issues:"
    echo "  - Invalid token"
    echo "  - Subdomain not registered at duckdns.org"
    echo "  - Network connectivity problem"
    exit 1
fi

# Create DuckDNS update script
echo ""
echo -e "${BLUE}📝 Creating DuckDNS update script...${NC}"
cat > "$DUCKDNS_UPDATE_SCRIPT" << EOF
#!/bin/bash
# DuckDNS Update Script for Goblin Assistant
# Auto-generated by setup-duckdns.sh

# Get current public IP
CURRENT_IP=\$(curl -s https://api.ipify.org)

# Update DuckDNS
RESPONSE=\$(curl -s "https://www.duckdns.org/update?domains=${DUCKDNS_DOMAIN}&token=${DUCKDNS_TOKEN}&ip=\${CURRENT_IP}")

# Log the result
TIMESTAMP=\$(date '+%Y-%m-%d %H:%M:%S')
if [ "\$RESPONSE" = "OK" ]; then
    echo "[\$TIMESTAMP] ✅ DuckDNS updated: ${DUCKDNS_DOMAIN}.duckdns.org -> \$CURRENT_IP" >> ${DUCKDNS_CRON_LOG}
    exit 0
else
    echo "[\$TIMESTAMP] ❌ DuckDNS update failed: \$RESPONSE" >> ${DUCKDNS_CRON_LOG}
    exit 1
fi
EOF

chmod +x "$DUCKDNS_UPDATE_SCRIPT"
echo -e "${GREEN}✅ Update script created: $DUCKDNS_UPDATE_SCRIPT${NC}"

# Create log file
touch "$DUCKDNS_CRON_LOG"
chmod 644 "$DUCKDNS_CRON_LOG"

# Setup cron job to update every 5 minutes
echo ""
echo -e "${BLUE}⏰ Setting up automatic updates (every 5 minutes)...${NC}"

# Remove existing DuckDNS cron jobs
crontab -l 2>/dev/null | grep -v "duckdns-update.sh" | crontab - || true

# Add new cron job
(crontab -l 2>/dev/null; echo "*/5 * * * * $DUCKDNS_UPDATE_SCRIPT") | crontab -

echo -e "${GREEN}✅ Cron job configured${NC}"

# Create environment file for docker-compose
echo ""
echo -e "${BLUE}📄 Creating environment configuration...${NC}"
ENV_FILE="/root/goblin-assistant/.env.duckdns"
cat > "$ENV_FILE" << EOF
# DuckDNS Configuration for Goblin Assistant
DUCKDNS_DOMAIN=${DUCKDNS_DOMAIN}
DUCKDNS_TOKEN=${DUCKDNS_TOKEN}
DUCKDNS_FULL_DOMAIN=${DUCKDNS_DOMAIN}.duckdns.org
PUBLIC_IP=${PUBLIC_IP}

# Update these in your main .env file:
# BACKEND_URL=https://${DUCKDNS_DOMAIN}.duckdns.org
# FRONTEND_URL=https://${DUCKDNS_DOMAIN}.duckdns.org
# API_BASE_URL=https://${DUCKDNS_DOMAIN}.duckdns.org/api
EOF

chmod 600 "$ENV_FILE"
echo -e "${GREEN}✅ Environment file created: $ENV_FILE${NC}"

# Display nginx configuration suggestion
echo ""
echo -e "${BLUE}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║     Next Steps: Nginx & SSL Configuration               ║${NC}"
echo -e "${BLUE}╚══════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${YELLOW}1. Install Certbot for SSL:${NC}"
echo "   sudo apt-get update"
echo "   sudo apt-get install -y certbot python3-certbot-nginx"
echo ""
echo -e "${YELLOW}2. Get SSL certificate:${NC}"
echo "   sudo certbot --nginx -d ${DUCKDNS_DOMAIN}.duckdns.org"
echo ""
echo -e "${YELLOW}3. Update nginx configuration:${NC}"
echo "   Edit /etc/nginx/sites-available/goblin-assistant"
echo "   Update server_name to: ${DUCKDNS_DOMAIN}.duckdns.org"
echo ""
echo -e "${YELLOW}4. Update Goblin Assistant environment:${NC}"
echo "   Source the DuckDNS environment file:"
echo "   source $ENV_FILE"
echo ""
echo -e "${YELLOW}5. Restart services:${NC}"
echo "   sudo systemctl restart nginx"
echo "   docker-compose restart"
echo ""
echo -e "${GREEN}✅ DuckDNS Setup Complete!${NC}"
echo ""
echo -e "${BLUE}Your domain: https://${DUCKDNS_DOMAIN}.duckdns.org${NC}"
echo ""
echo -e "${YELLOW}📊 Monitor updates:${NC}"
echo "   tail -f $DUCKDNS_CRON_LOG"
echo ""
echo -e "${YELLOW}🔄 Manual update:${NC}"
echo "   sudo $DUCKDNS_UPDATE_SCRIPT"
echo ""
