---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: datadog-agent
  namespace: goblin-assistant
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datadog-agent
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - events
      - endpoints
      - pods
      - nodes
      - componentstatuses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - datadog-leader-election
      - datadog-cluster-id
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
  - nonResourceURLs:
      - /version
      - /healthz
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
      - daemonsets
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: datadog-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: datadog-agent
subjects:
  - kind: ServiceAccount
    name: datadog-agent
    namespace: goblin-assistant
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: datadog-agent
  namespace: goblin-assistant
spec:
  selector:
    matchLabels:
      app: datadog-agent
  template:
    metadata:
      labels:
        app: datadog-agent
      name: datadog-agent
    spec:
      serviceAccountName: datadog-agent
      hostPID: true  # Required for process monitoring
      hostNetwork: true  # Optional but recommended

      containers:
        - name: agent
          image: gcr.io/datadoghq/agent:7

          env:
            # API Key from secret
            - name: DD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: datadog-secret
                  key: api-key

            # Basic Configuration
            - name: DD_SITE
              value: "datadoghq.com"
            - name: DD_KUBERNETES_KUBELET_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_ENV
              value: "production"
            - name: DD_TAGS
              value: "env:production service:goblin-assistant project:forge-monorepo"

            # Process Collection
            - name: DD_PROCESS_AGENT_ENABLED
              value: "true"
            - name: DD_PROCESS_CONFIG_RUN_IN_CORE_AGENT
              value: "true"
            - name: DD_PROCESS_CONFIG_SCRUB_ARGS
              value: "true"
            - name: DD_PROCESS_CONFIG_CUSTOM_SENSITIVE_WORDS
              value: "api_key,apikey,token,secret,password,credential"

            # System Probe
            - name: DD_SYSTEM_PROBE_ENABLED
              value: "true"
            - name: DD_SYSTEM_PROBE_PROCESS_ENABLED
              value: "true"

            # Container Collection
            - name: DD_CONTAINER_COLLECT_ALL
              value: "true"
            - name: DD_DOCKER_LABELS_AS_TAGS
              value: '{"*":true}'
            - name: DD_KUBERNETES_POD_LABELS_AS_TAGS
              value: '{"*":true}'

            # APM
            - name: DD_APM_ENABLED
              value: "true"
            - name: DD_APM_NON_LOCAL_TRAFFIC
              value: "true"

            # Logs
            - name: DD_LOGS_ENABLED
              value: "true"
            - name: DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL
              value: "true"

            # DogStatsD
            - name: DD_DOGSTATSD_NON_LOCAL_TRAFFIC
              value: "true"

          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"

          volumeMounts:
            # Required for process monitoring
            - name: dockersocket
              mountPath: /var/run/docker.sock
              readOnly: true
            - name: procdir
              mountPath: /host/proc
              readOnly: true
            - name: cgroups
              mountPath: /host/sys/fs/cgroup
              readOnly: true
            - name: passwd
              mountPath: /etc/passwd
              readOnly: true

            # System probe
            - name: debugfs
              mountPath: /sys/kernel/debug
              readOnly: true
            - name: modules
              mountPath: /lib/modules
              readOnly: true

            # Agent state
            - name: pointerdir
              mountPath: /opt/datadog-agent/run

          securityContext:
            privileged: true  # Required for system-probe
            capabilities:
              add:
                - SYS_ADMIN
                - SYS_RESOURCE
                - SYS_PTRACE
                - NET_ADMIN
                - NET_BROADCAST
                - NET_RAW
                - IPC_LOCK

      volumes:
        - name: dockersocket
          hostPath:
            path: /var/run/docker.sock
        - name: procdir
          hostPath:
            path: /proc
        - name: cgroups
          hostPath:
            path: /sys/fs/cgroup
        - name: passwd
          hostPath:
            path: /etc/passwd
        - name: debugfs
          hostPath:
            path: /sys/kernel/debug
        - name: modules
          hostPath:
            path: /lib/modules
        - name: pointerdir
          hostPath:
            path: /opt/datadog-agent/run
---
apiVersion: v1
kind: Secret
metadata:
  name: datadog-secret
  namespace: goblin-assistant
type: Opaque
data:
  # Replace with base64 encoded API key: echo -n "YOUR_API_KEY" | base64
  api-key: YOUR_BASE64_ENCODED_API_KEY_HERE
