#!/bin/bash
# Deploy GoblinOS Assistant Backend to Render

set -e  # Exit on error

echo "🚀 Deploying GoblinOS Assistant Backend to Render..."

# Navigate to backend directory
cd "$(dirname "$0")/backend"

echo "📦 Installing dependencies..."
pip install -r requirements.txt

echo "🗄️  Running database migrations..."
python init_db.py

echo "✅ Backend ready for deployment!"
echo ""
echo "To deploy to Render:"
echo "1. Push changes to GitHub"
echo "2. Render will automatically detect and deploy"
echo "3. Or manually trigger deployment in Render dashboard"
echo ""
echo "Environment variables to set in Render:"
echo "- DATABASE_URL (from Render PostgreSQL)"
echo "- LOCAL_LLM_PROXY_URL=http://45.61.60.3:8002"
echo "- LOCAL_LLM_API_KEY=<your-kamatera-api-key>"
echo "- All API keys (OpenAI, Anthropic, etc.)"
echo "- JWT secrets (auto-generated by Render)"
echo ""
echo "See DEPLOYMENT_ARCHITECTURE.md for full details"
