apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki-s3-es
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secretstore
    kind: SecretStore
  target:
    name: loki-s3-credentials
    creationPolicy: Owner
  data:
    - secretKey: aws_access_key_id
      remoteRef:
        key: secret/data/loki
        property: aws_access_key_id
    - secretKey: aws_secret_access_key
      remoteRef:
        key: secret/data/loki
        property: aws_secret_access_key
