apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-kubernetes-auth
  namespace: observability
spec:
  provider:
    vault:
      server: "${VAULT_ADDR}"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          role: external-secrets-role
