name: Cost Estimate Check
on:
  pull_request:
    paths:
      - 'envs/**'
      - 'modules/**'
permissions:
  contents: read
  pull-requests: write
jobs:
  infracost:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}
        continue-on-error: true

      - name: Generate cost estimate (dev)
        id: cost-dev
        run: |
          if command -v infracost &> /dev/null; then
            infracost breakdown --path=envs/dev --format=json --out-file=/tmp/dev.json || true
            COST=$(jq -r '.totalMonthlyCost // "N/A"' /tmp/dev.json 2>/dev/null || echo "N/A")
            echo "dev_cost=$COST" >> $GITHUB_OUTPUT
          else
            echo "dev_cost=Infracost not configured" >> $GITHUB_OUTPUT
          fi
        continue-on-error: true

      - name: Generate cost estimate (staging)
        id: cost-staging
        run: |
          if command -v infracost &> /dev/null; then
            infracost breakdown --path=envs/staging --format=json --out-file=/tmp/staging.json || true
            COST=$(jq -r '.totalMonthlyCost // "N/A"' /tmp/staging.json 2>/dev/null || echo "N/A")
            echo "staging_cost=$COST" >> $GITHUB_OUTPUT
          else
            echo "staging_cost=Infracost not configured" >> $GITHUB_OUTPUT
          fi
        continue-on-error: true

      - name: Generate cost estimate (prod)
        id: cost-prod
        run: |
          if command -v infracost &> /dev/null; then
            infracost breakdown --path=envs/prod --format=json --out-file=/tmp/prod.json || true
            COST=$(jq -r '.totalMonthlyCost // "N/A"' /tmp/prod.json 2>/dev/null || echo "N/A")
            echo "prod_cost=$COST" >> $GITHUB_OUTPUT
          else
            echo "prod_cost=Infracost not configured" >> $GITHUB_OUTPUT
          fi
        continue-on-error: true

      - name: Post cost summary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}

          gh pr comment $PR_NUMBER --body "## 💰 Cost Estimate

| Environment | Monthly Cost |
|-------------|--------------|
| Dev | ${{ steps.cost-dev.outputs.dev_cost }} |
| Staging | ${{ steps.cost-staging.outputs.staging_cost }} |
| Prod | ${{ steps.cost-prod.outputs.prod_cost }} |

---
*To enable detailed cost estimates, add \`INFRACOST_API_KEY\` to repository secrets.*"
        continue-on-error: true
