name: PR IaC Checks
on:
  pull_request:
    paths:
      - 'envs/**'
      - 'modules/**'
permissions:
  contents: read
  pull-requests: write
  id-token: write
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform fmt (dev)
        run: terraform -chdir=envs/dev fmt -check
        continue-on-error: true

      - name: Terraform fmt (staging)
        run: terraform -chdir=envs/staging fmt -check
        continue-on-error: true

      - name: Terraform fmt (prod)
        run: terraform -chdir=envs/prod fmt -check
        continue-on-error: true

      - name: Terraform validate (dev)
        run: |
          terraform -chdir=envs/dev init -backend=false
          terraform -chdir=envs/dev validate

      - name: Terraform validate (staging)
        run: |
          terraform -chdir=envs/staging init -backend=false
          terraform -chdir=envs/staging validate

      - name: Terraform validate (prod)
        run: |
          terraform -chdir=envs/prod init -backend=false
          terraform -chdir=envs/prod validate

      - name: Install tfsec
        run: |
          curl -sSfL https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

      - name: tfsec scan (dev)
        run: tfsec envs/dev --soft-fail

      - name: tfsec scan (staging)
        run: tfsec envs/staging --soft-fail

      - name: tfsec scan (prod)
        run: tfsec envs/prod --soft-fail

      - name: Install checkov
        run: pip install checkov

      - name: Checkov scan
        run: checkov -d envs/ --soft-fail

      - name: Post check summary
        run: |
          echo "## IaC Checks Complete" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Terraform fmt" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Terraform validate" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ tfsec security scan" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Checkov compliance scan" >> $GITHUB_STEP_SUMMARY
