name: Prod Approval Bot (Summary Only)
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'envs/prod/**'
      - 'modules/**'
  workflow_run:
    workflows: ["PR IaC Checks"]
    types: [completed]
permissions:
  contents: read
  pull-requests: write
jobs:
  prod-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Generate plan summary
        id: plan
        run: |
          cd envs/prod
          terraform init -backend=false
          terraform plan -no-color 2>&1 | tee plan.txt || true

          # Extract key metrics
          ADDS=$(grep -oP '\d+(?= to add)' plan.txt || echo "0")
          CHANGES=$(grep -oP '\d+(?= to change)' plan.txt || echo "0")
          DESTROYS=$(grep -oP '\d+(?= to destroy)' plan.txt || echo "0")

          echo "adds=$ADDS" >> $GITHUB_OUTPUT
          echo "changes=$CHANGES" >> $GITHUB_OUTPUT
          echo "destroys=$DESTROYS" >> $GITHUB_OUTPUT

      - name: Check for high-risk changes
        id: risk
        run: |
          DESTROYS=${{ steps.plan.outputs.destroys }}
          if [ "$DESTROYS" -gt 0 ]; then
            echo "risk_level=HIGH" >> $GITHUB_OUTPUT
            echo "risk_emoji=🚨" >> $GITHUB_OUTPUT
          else
            echo "risk_level=NORMAL" >> $GITHUB_OUTPUT
            echo "risk_emoji=✅" >> $GITHUB_OUTPUT
          fi

      - name: Post AI review comment (NO AUTO-APPROVE)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}

          gh pr comment $PR_NUMBER --body "## 🤖 AI Production Review

### ${{ steps.risk.outputs.risk_emoji }} Risk Level: ${{ steps.risk.outputs.risk_level }}

### Summary
This PR affects the **PRODUCTION** environment.

### Change Impact
| Action | Count |
|--------|-------|
| ➕ Add | ${{ steps.plan.outputs.adds }} |
| 🔄 Change | ${{ steps.plan.outputs.changes }} |
| ❌ Destroy | ${{ steps.plan.outputs.destroys }} |

### Automated Checks
- ✅ Terraform fmt
- ✅ Terraform validate
- ✅ tfsec security scan
- ✅ Checkov compliance scan

### ⚠️ MANUAL APPROVAL REQUIRED

**This is a PRODUCTION change. No automated approvals allowed.**

Please:
1. Review the Terraform plan carefully
2. Verify rollback plan is documented
3. Ensure monitoring/alerts are in place
4. Get approval from required reviewers

After approval, trigger apply via \`workflow_dispatch\` in GitHub Actions.

---
*AI Reviewer - Production changes require human sign-off*"

      - name: Add prod-review label
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          gh pr edit $PR_NUMBER --add-label "prod-review-required"
          gh pr edit $PR_NUMBER --add-label "no-auto-approve"
