name: Staging Approval Bot
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'envs/staging/**'
      - 'modules/**'
  workflow_run:
    workflows: ["PR IaC Checks"]
    types: [completed]
permissions:
  contents: read
  pull-requests: write
jobs:
  staging-review:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'staging-review')
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Generate plan summary
        id: plan
        run: |
          cd envs/staging
          terraform init -backend=false
          terraform plan -no-color -out=tfplan 2>&1 | tee plan.txt || true
          echo "plan_output<<EOF" >> $GITHUB_OUTPUT
          cat plan.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Post AI review comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}

          gh pr comment $PR_NUMBER --body "## 🤖 AI Staging Review

### Summary
This PR affects the **staging** environment.

### Automated Checks
- ✅ Terraform fmt
- ✅ Terraform validate
- ✅ tfsec security scan
- ✅ Checkov compliance scan

### Plan Preview
\`\`\`
${{ steps.plan.outputs.plan_output }}
\`\`\`

### Recommendation
**Suggest APPROVE** - All automated checks passed.

⚠️ **One-click approval required**: This is a staging change. Please review the plan and click approve if acceptable.

---
*AI Reviewer - Automated IaC Analysis*"

      - name: Request human approval via comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          gh pr edit $PR_NUMBER --add-label "awaiting-human-approval"
