name: Terraform Apply (dev)
on:
  push:
    branches:
      - main
    paths:
      - 'envs/dev/**'
      - 'modules/**'
permissions:
  contents: read
  id-token: write
jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      - name: Terraform Init
        run: terraform -chdir=envs/dev init -input=false
      - name: Terraform Apply
        env:
          AWS_REGION: us-east-1
        run: terraform -chdir=envs/dev apply -auto-approve -input=false
