name: Terraform Plan (staging)
on:
  pull_request:
    paths:
      - 'envs/staging/**'
      - 'modules/**'
permissions:
  contents: read
  id-token: write
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      - name: Terraform Fmt
        run: terraform -chdir=envs/staging fmt -check
      - name: Terraform Init
        run: terraform -chdir=envs/staging init -input=false
      - name: Terraform Validate
        run: terraform -chdir=envs/staging validate
      - name: Terraform Plan
        run: terraform -chdir=envs/staging plan -input=false -out=tfplan -no-color
      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: staging-tfplan
          path: envs/staging/tfplan
      - name: Post plan summary
        run: echo "Plan uploaded as artifact"
