name: Terraform Plan (dev)
on:
  pull_request:
    paths:
      - 'envs/dev/**'
      - 'modules/**'
permissions:
  contents: read
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      - name: Terraform Format
        run: terraform -chdir=envs/dev fmt -check
      - name: Terraform Init
        run: terraform -chdir=envs/dev init -input=false
      - name: Terraform Validate
        run: terraform -chdir=envs/dev validate
      - name: Terraform Plan
        run: terraform -chdir=envs/dev plan -input=false -no-color -out=tfplan
      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: envs/dev/tfplan
