apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: overmind-dev
  namespace: argocd
  labels:
    app: overmind
    env: dev
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  # Source repository
  source:
    repoURL: https://github.com/your-org/ForgeMonorepo.git
    targetRevision: main
    path: infra/overlays/dev

    # Kustomize configuration
    kustomize:
      version: v5.0.0
      # KSOPS plugin for SOPS secrets
      buildOptions: "--enable-alpha-plugins --enable-exec"

  # Destination cluster and namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: overmind-dev

  # Sync policy
  syncPolicy:
    # Automated sync
    automated:
      prune: true        # Remove resources not in Git
      selfHeal: true     # Revert manual changes
      allowEmpty: false  # Don't sync if no resources

    # Sync options
    syncOptions:
    - CreateNamespace=true           # Auto-create namespace
    - PrunePropagationPolicy=foreground  # Wait for dependents
    - PruneLast=true                 # Prune after sync
    - RespectIgnoreDifferences=true  # Honor ignoreDifferences

    # Retry policy
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Ignore differences (avoid drift alerts for these fields)
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas  # Ignore HPA-managed replicas
  - group: autoscaling
    kind: HorizontalPodAutoscaler
    jsonPointers:
    - /spec/minReplicas
    - /spec/maxReplicas

  # Resource tracking
  revisionHistoryLimit: 10
