#!/bin/bash
# ForgeMonorepo - Bitwarden Secret Manager
# Securely manages secrets using Bitwarden CLI instead of .env files
# Usage: ./tools/secrets.sh [command] [options]

set -e  # Exit on any error

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Logging functions
log_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

log_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

log_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

log_error() {
    echo -e "${RED}❌ $1${NC}"
}

# Check if Bitwarden CLI is installed
check_bw_cli() {
    if ! command -v bw &> /dev/null; then
        log_error "Bitwarden CLI not found. Installing..."
        npm install -g @bitwarden/cli
        log_success "Bitwarden CLI installed"
    fi
}

# Check if vault is unlocked
check_bw_session() {
    if [ -z "$BW_SESSION" ]; then
        log_warning "Bitwarden vault is locked. Unlocking..."
        export BW_SESSION=$(bw unlock --raw)
        if [ -z "$BW_SESSION" ]; then
            log_error "Failed to unlock Bitwarden vault"
            exit 1
        fi
        log_success "Bitwarden vault unlocked"
    fi
}

# Sync vault
sync_vault() {
    log_info "Syncing Bitwarden vault..."
    bw sync
    log_success "Vault synced"
}

# Get a secret by name
get_secret() {
    local secret_name="$1"
    local secret_value

    check_bw_session
    sync_vault

    secret_value=$(bw get password "$secret_name" 2>/dev/null)
    if [ -z "$secret_value" ]; then
        log_error "Secret '$secret_name' not found in Bitwarden"
        return 1
    fi

    echo "$secret_value"
}

# Set a secret (creates or updates)
set_secret() {
    local secret_name="$1"
    local secret_value="$2"
    local notes="$3"

    check_bw_session

    # Check if secret already exists
    if bw get password "$secret_name" &>/dev/null; then
        log_info "Updating existing secret: $secret_name"
        # For updates, we'd need to use bw edit, but that's more complex
        # For now, just warn the user
        log_warning "Secret '$secret_name' already exists. Use Bitwarden UI to update."
        return 1
    else
        log_info "Creating new secret: $secret_name"
        # Create a new secure note
        echo "{\"type\":1,\"name\":\"$secret_name\",\"notes\":\"$notes\",\"login\":null,\"fields\":[{\"name\":\"password\",\"value\":\"$secret_value\",\"type\":0}]}" | bw create item
        log_success "Secret '$secret_name' created"
    fi
}

# List all secrets (names only)
list_secrets() {
    check_bw_session
    sync_vault

    log_info "Available secrets:"
    bw list items --search "goblin-" | jq -r '.[].name' | sort
}

# Load secrets for a specific app
load_app_secrets() {
    local app_name="$1"
    local env_file="${PROJECT_ROOT}/apps/${app_name}/.env"

    log_info "Loading secrets for app: $app_name"

    # Create .env file with secrets from Bitwarden
    cat > "$env_file" << EOF
# Generated by ForgeMonorepo Secret Manager
# DO NOT EDIT - This file is auto-generated from Bitwarden
# Last updated: $(date)

EOF

    # Load common secrets
    load_secret_to_env "goblin-${app_name}-openai" "OPENAI_API_KEY" "$env_file"
    load_secret_to_env "goblin-${app_name}-anthropic" "ANTHROPIC_API_KEY" "$env_file"
    load_secret_to_env "goblin-${app_name}-supabase-url" "SUPABASE_URL" "$env_file"
    load_secret_to_env "goblin-${app_name}-supabase-anon" "SUPABASE_ANON_KEY" "$env_file"

    log_success "Secrets loaded to $env_file"
    log_warning "Remember to add $env_file to .gitignore!"
}

# Helper to load a secret to .env file
load_secret_to_env() {
    local secret_name="$1"
    local env_var="$2"
    local env_file="$3"

    local secret_value
    secret_value=$(get_secret "$secret_name" 2>/dev/null)
    if [ -n "$secret_value" ]; then
        echo "$env_var=$secret_value" >> "$env_file"
    fi
}

# Monitor for unauthorized .env files
monitor_env_files() {
    log_info "Monitoring for unauthorized .env files..."

    # Find all .env files
    local env_files
    env_files=$(find "$PROJECT_ROOT" -name "*.env" -type f 2>/dev/null)

    local unauthorized_files=()

    while IFS= read -r file; do
        # Skip allowed .env files
        if [[ "$file" == *".env.example" ]] || [[ "$file" == *".env.template" ]]; then
            continue
        fi

        # Check if file contains real secrets (not placeholders)
        if grep -q "sk-\|AIza\|SECRET\|TOKEN\|PASSWORD" "$file" 2>/dev/null; then
            unauthorized_files+=("$file")
        fi
    done <<< "$env_files"

    if [ ${#unauthorized_files[@]} -gt 0 ]; then
        log_error "Found unauthorized .env files with potential secrets:"
        printf '%s\n' "${unauthorized_files[@]}"
        log_warning "These files should be removed and secrets moved to Bitwarden"
        return 1
    else
        log_success "No unauthorized .env files found"
    fi
}

# Clean up generated .env files
cleanup_env_files() {
    log_info "Cleaning up generated .env files..."

    find "$PROJECT_ROOT" -name ".env" -type f -exec rm -f {} \; 2>/dev/null
    log_success "Generated .env files removed"
}

# Main command handler
main() {
    local command="$1"
    shift

    check_bw_cli

    case "$command" in
        "get")
            local secret_name="$1"
            if [ -z "$secret_name" ]; then
                log_error "Usage: $0 get <secret-name>"
                exit 1
            fi
            get_secret "$secret_name"
            ;;
        "set")
            local secret_name="$1"
            local secret_value="$2"
            if [ -z "$secret_name" ] || [ -z "$secret_value" ]; then
                log_error "Usage: $0 set <secret-name> <secret-value> [notes]"
                exit 1
            fi
            set_secret "$secret_name" "$secret_value" "$3"
            ;;
        "list")
            list_secrets
            ;;
        "load")
            local app_name="$1"
            if [ -z "$app_name" ]; then
                log_error "Usage: $0 load <app-name>"
                exit 1
            fi
            load_app_secrets "$app_name"
            ;;
        "monitor")
            monitor_env_files
            ;;
        "cleanup")
            cleanup_env_files
            ;;
        "help"|*)
            echo "ForgeMonorepo Bitwarden Secret Manager"
            echo ""
            echo "Usage: $0 <command> [options]"
            echo ""
            echo "Commands:"
            echo "  get <name>        Get a secret value"
            echo "  set <name> <val>  Set a secret value"
            echo "  list              List all secrets"
            echo "  load <app>        Load secrets for an app"
            echo "  monitor           Check for unauthorized .env files"
            echo "  cleanup           Remove generated .env files"
            echo "  help              Show this help"
            echo ""
            echo "Examples:"
            echo "  $0 get goblin-prod-openai"
            echo "  $0 set my-secret 'secret-value' 'My secret notes'"
            echo "  $0 load goblin-assistant"
            echo "  $0 monitor"
            ;;
    esac
}

# Run main function with all arguments
main "$@"
