#!/bin/bash
# Responsive Layout Visual Testing Script
# Run this to open browser at different viewport sizes

echo "🎨 Goblin Assistant - Responsive Layout Testing"
echo "==============================================="
echo ""
echo "Dev server should be running at http://localhost:5173"
echo ""
echo "VIEWPORT TESTING INSTRUCTIONS:"
echo ""
echo "1. Open Chrome and navigate to: http://localhost:5173/dashboard"
echo "2. Open DevTools: Cmd+Option+I (Mac) or F12 (Windows/Linux)"
echo "3. Click Device Toolbar icon: Cmd+Shift+M or Ctrl+Shift+M"
echo "4. Select 'Responsive' from device dropdown"
echo ""
echo "TEST THESE WIDTHS IN ORDER:"
echo ""
echo "┌─────────┬──────────────────┬──────────────────┐"
echo "│ Width   │ Device Type      │ Expected Layout  │"
echo "├─────────┼──────────────────┼──────────────────┤"
echo "│ 375px   │ Mobile (iPhone)  │ 1 column         │"
echo "│ 768px   │ Tablet (iPad)    │ 2 columns        │"
echo "│ 1024px  │ Small Desktop    │ 3 columns        │"
echo "│ 1280px  │ Desktop          │ 3-4 columns      │"
echo "│ 1440px  │ Wide Desktop     │ 4 columns        │"
echo "└─────────┴──────────────────┴──────────────────┘"
echo ""
echo "WHAT TO CHECK:"
echo ""
echo "Layout:"
echo "  [ ] Cards stack properly (no overflow)"
echo "  [ ] Consistent gap spacing (1rem)"
echo "  [ ] No horizontal scrolling"
echo "  [ ] Grid adapts smoothly between breakpoints"
echo ""
echo "Components:"
echo "  [ ] StatusCard meta grid adapts (2-col on mobile, 3-col on tablet+)"
echo "  [ ] Navigation wraps on mobile, stays horizontal on desktop"
echo "  [ ] Header flex layout stacks on mobile (flex-col → flex-row)"
echo "  [ ] Cost stat cards display properly"
echo "  [ ] Quick action buttons remain accessible"
echo ""
echo "Typography:"
echo "  [ ] Text readable at all sizes (min 14px body)"
echo "  [ ] No text overflow or truncation"
echo "  [ ] Line heights prevent cramping"
echo "  [ ] Headings scale appropriately"
echo ""
echo "Accessibility:"
echo "  [ ] Touch targets at least 44x44px (mobile)"
echo "  [ ] Focus indicators visible on all interactive elements"
echo "  [ ] Keyboard navigation works at all sizes"
echo "  [ ] Skip link appears on Tab (desktop)"
echo ""
echo "Performance:"
echo "  [ ] No jank during window resize"
echo "  [ ] Smooth transitions between breakpoints"
echo "  [ ] Images/icons scale without distortion"
echo ""
echo "==============================================="
echo ""
echo "Press ENTER to open Chrome DevTools documentation..."
read

open "https://developer.chrome.com/docs/devtools/device-mode/"
